name: Spells
main: me.hgilman.Spells.Spells
version: 2.0
commands:
   spellinfo:
      description: Gives the description of the specified or current spell.
      permission: Spells.spellinfo
      usage: /spellinfo [spell]
   listspells:
      description: Lists the available spells.
      permission: Spells.listspells
      usage: /listspells
   setspell:
      description: Sets the current spell.
      permission: Spells.setspell
      usage: /setspell [spell]