name: Spells
main: me.hgilman.Spells.Spells
version: 2.0
commands:
   spellinfo:
      description: Gives the description of the specified or current spell.
      permission: Spells.spellinfo
      usage: /spellinfo [spell]